### ISSUE TITLE
Bug: Exception gets thrown when trying to extract

### ISSUE THREAD

**Issue by BoBoBaSs84** [MadDeCoDeR/BFG-Resource-File-Manager#6]
**Describe the bug**
When trying to extract the common resource file an unhandled exception gets thrown.

**To Reproduce**
1. Open the common resource file
2. Click on extract archive
3. See the unhandled exception

**Expected behavior**
Every thing should get extracted. No exception gets thrown within the method `ExtractFolder(string relativePath, string outputFolder)`.

**Additional context**
The reason is, when an archive has a file with no relative path (`root` only), calling `LastIndexOf("/")` leads to an exception since there is no last index for using the method `Substring(int startIndex, int length`.

**Comment by Probotus** [comment]
Can confirm this.

![Capture_common_file](https://github.com/MadDeCoDeR/BFG-Resource-File-Manager/assets/137200367/39569988-212c-47c4-8fb8-9b41161a13f9)

And on clicking extract folder:

![Capture_exception](https://github.com/MadDeCoDeR/BFG-Resource-File-Manager/assets/137200367/3b64767f-cf53-4f24-9aaf-7708d011cd7a)

**Comment by BoBoBaSs84** [comment]
Jup the _common.preload is the issue, or how it gets handled.
